### ISSUE TITLE
Fail to install beautifulsoup

### ISSUE THREAD

**Issue by zzllyyjj** [damasktb/NewsGraph#12]
When I run pip install -r requirements.txt, there's an error:
 File "C:\Users\hp\AppData\Local\Temp\pip-install-z8q0r6d5\beautifulsoup\setup.py", line 3
        "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."

How can I solve this problem?

**Comment by damasktb** [comment]
Hi - I’m not actively maintaining this project but I developed it in Python 2.7, and the error you’re seeing is because you’re using Python 3. You can either use 2.7, or experiment with manually upgrading the dependencies!

**Comment by zzllyyjj** [comment]
Thank you! But I have upgraded the BeautifulSoup(now its version is 4.6.3 and it's in the path：anaconda/lib/site-packages). Then when I try to run pip install -r requirements.txt again, the same error occurred. I don't know why.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Damask Talary-Brown"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 凌晨4:36
收件人:&nbsp;"damasktb/NewsGraph"<NewsGraph@noreply.github.com&gt;;
抄送:&nbsp;"zlyj"<1246975215@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [damasktb/NewsGraph] Fail to install beautifulsoup (#12)




Hi - I’m not actively maintaining this project but I developed it in Python 2.7, and the error you’re seeing is because you’re using Python 3. You can either use 2.7, or experiment with manually upgrading the dependencies!

**Comment by damasktb** [comment]
You’d need to use pip2 or similar otherwise it’s still going to use python 3...

**Comment by zzllyyjj** [comment]
Oh, I see. Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Damask Talary-Brown"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月20日(星期五) 下午4:03
收件人:&nbsp;"damasktb/NewsGraph"<NewsGraph@noreply.github.com&gt;;
抄送:&nbsp;"zlyj"<1246975215@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [damasktb/NewsGraph] Fail to install beautifulsoup (#12)




You’d need to use pip2 or similar otherwise it’s still going to use python 3...
